SELECT trim(SPON_CD) as SPON_CD, SPON_AGCY_CD, SPON_AGCY_NAM, trim(SPON_AGCY_SHRT_NAM) as SPON_AGCY_SHRT_NAM
FROM SP_BI.SPONSOR_D 
WHERE SPON_CUR_ACTV_FL='Y' AND SPON_CD NOT IN('','000000000') AND SPON_CD IS NOT NULL
AND SPON_AGCY_CD <> '  '